README.md
docs/api/footerMenu.md
src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
src/lib/components/02-components/menus/footer/footer-menu.tsx
src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
src/lib/components/index.ts

- [FP-340: Footer Menu](https://fourkitchens.clickup.com/t/36718269/FP-340)
Create the Footer Menu component

FP-340: Footer menu

---

src/lib/components/01-elements/button/button.stories.tsx
src/lib/components/01-elements/button/button.tsx
src/lib/components/01-elements/link/link.stories.tsx
src/lib/components/01-elements/link/link.tsx
src/lib/components/02-components/ctas/main-nav-link/main-nav-link.tsx
src/lib/components/02-components/ctas/nav-link/nav-link.tsx
src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
src/lib/components/02-components/menus/main-menu/main-menu.tsx
src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx

- [FP-736: Update CTA and button Styles](https://fourkitchens.clickup.com/t/36718269/FP-736)
Update link and button styles with figma.
- Link
- Button.
- Main menu.
- Secondary menu.
- [Design](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=0-1&mode=design&t=BLV7QPVQT08ZrsJY-0)

FP-736: Update CTA and button Styles

---

README.md
docs/api/callout.md
src/lib/components/02-components/callout/callout.stories.tsx
src/lib/components/02-components/callout/callout.tsx
tailwind-theme-preset.js

- [FP-280: Callout - FE](https://fourkitchens.clickup.com/t/36718269/FP-280)
Update link and button styles with figma.
- [Design](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2290-137029&mode=design&t=VPCJlAhLZR8m1302-0)

FP-280: Callout - FE

---

docs/api/callout.md
src/lib/components/01-elements/button/button.tsx
src/lib/components/02-components/callout/callout.tsx
src/lib/components/index.ts

- [FP-750: Callout - Wiring](https://fourkitchens.clickup.com/t/36718269/FP-750)
- Update callout paragraph to match GraphQL

FP-750: Callout - Wiring

---

docs/api/mainMenu.md
src/lib/components/02-components/ctas/nav-link/nav-link.tsx
src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
src/lib/components/02-components/menus/main-menu/main-menu.tsx

- [FP-764: Main nav FED follow ups](https://fourkitchens.clickup.com/t/36718269/FP-764)
- Change prop field name to match GraphQL
- Change gap value

FP-764: Main nav FED follow ups

---

docs/api/hubspotFormWrapper.md
package.json
src/lib/assets/css/form.css
src/lib/assets/img/icons/arrow-right-white.svg
src/lib/components/02-components/form/hubspot-form-wrapper.stories.tsx
src/lib/components/02-components/form/hubspot-form-wrapper.tsx
src/lib/components/index.ts
tailwind-theme-preset.js

- [FP-252: External Form (hubspot) ](https://fourkitchens.clickup.com/t/36718269/FP-252)
- Updates `form` styles
- Adds an `HubspotFormWrapper` component
- Required by: https://github.com/fourkitchens/forcepoint-nextjs-page-router/pull/34
- Marge this PR to `main` branch
- Update the [Next.js app](https://github.com/fourkitchens/forcepoint-nextjs-page-router) reference by running: `npm install github:fourkitchens/forcepoint-shared-components`

FP-252: External Form (hubspot)

---

docs/api/stickyHeader.md
src/lib/assets/img/branding/logo-white.svg
src/lib/components/01-elements/button/button.tsx
src/lib/components/02-components/sticky-header/sticky-header.stories.tsx
src/lib/components/02-components/sticky-header/sticky-header.tsx
src/lib/components/index.ts

- [FP-270: Product - FED](https://fourkitchens.clickup.com/t/36718269/FP-270)
- Create a sticky header

FP-270: Sticky Header Component

---

src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
src/lib/components/02-components/menus/footer/footer-menu.tsx
src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx

- [FP-809: Fix Footer Spacing & Last Link Format](https://fourkitchens.clickup.com/t/36718269/FP-809)
- Adds support for user defined classes in footer menu, needed to set a different style in the "All Products" and "All Solutions"  links

FP-809: Support for user defined classes in footer menu

---

src/lib/components/02-components/menus/language-switcher/language-switcher.tsx

- [FP-825: Follow ups to home page after domain masking](https://fourkitchens.clickup.com/t/36718269/FP-825)
- Adds support to anchor tags to language switcher component
- (optional) Document any unique steps required to deploy this PR (if any)
- Example: Once PR is merged and deployed to remote environment go to [page link] and manually sync data from Live25.
- (optional) Describes changes made to the project's README file
- Security checks that should be reviewed
- Should this be checked for this feature?
- (optional) Document any intentionally unfinished parts or known issues within this PR

feat: support anchor tags

---

src/lib/assets/css/form.css
src/lib/assets/css/main-menu.css
src/lib/components/01-elements/link/link.tsx
src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
src/lib/components/02-components/menus/main-menu/main-menu.tsx
src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
src/lib/components/02-components/search-input/search-input.tsx

- [FP-823: Header Changes](https://fourkitchens.clickup.com/t/36718269/FP-823)
- Style updates to [address feedback](https://miro.com/app/board/uXjVKZJONU0=/)

FP-823: Header Changes

---

src/lib/assets/css/main-menu.css
src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
src/lib/components/02-components/ctas/nav-link/nav-link.tsx
src/lib/components/02-components/menus/main-menu/main-menu.tsx

- Match style with prod site
- Feedback in the (Miro board)[https://miro.com/app/board/uXjVKOcALLk=/]

Match navigation style with prod

---

src/lib/assets/css/main-menu.css
src/lib/components/02-components/ctas/nav-link/nav-link.tsx

- Adjust spacing
Before:
After:

Navbar fixes

---

README.md
docs/api/callout.md
docs/api/featuredResourceCard.md
docs/api/featuredResourceListItem.md
src/lib/assets/img/icons/download.svg
src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
src/lib/components/02-components/featured-resource/featured-resource--card.tsx
src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
src/lib/components/index.ts

- [FP-376:  Featured resource](https://fourkitchens.clickup.com/t/36718269/FP-376)
- Adds a `featured resource` component.
- https://github.com/fourkitchens/forcepoint-nextjs-page-router/pull/55
- https://github.com/fourkitchens/forcepoint-drupal/pull/93
- [Card version](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2256-129374&mode=design&t=aDa2TsAcVKMllX9K-0)
- [List version](https://www.figma.com/file/HwazkcYwlIm9Yz6NwIQ1b3/Web-Standards?type=design&node-id=2269-129495&mode=design&t=aDa2TsAcVKMllX9K-0)

FP-294:  Featured resource.

---

src/lib/assets/img/icons/circle-checkmark.svg
src/lib/components/02-components/list-item/list-item.stories.tsx
src/lib/components/02-components/list-item/list-item.tsx
src/lib/components/02-components/list/list.stories.tsx
src/lib/components/02-components/list/list.tsx
src/lib/components/index.ts

- [FP-304: List + List Item FED](https://fourkitchens.clickup.com/t/36718269/FP-304)
- Add List Item component
- Add List component

FP-304: List + List Item components

---

docs/api/languageSwitcher.md
src/lib/components/02-components/menus/language-switcher/language-switcher.stories.tsx
src/lib/components/02-components/menus/language-switcher/language-switcher.tsx

- [FP-834: Language switcher is not changing site language](https://fourkitchens.clickup.com/t/36718269/FP-834)

feat(834): Excluded lancode support added for language switcher

---

src/lib/components/02-components/form/site-search/site-search.tsx

- [FP-434: Search - FED](https://fourkitchens.clickup.com/t/36718269/FP-434)
- Follow-up ticket to add missing styles
Base PR https://github.com/fourkitchens/forcepoint-shared-components/pull/72

FP-434: Search Follow up

---

docs/api/img.md
src/lib/components/01-elements/img/img.stories.tsx
src/lib/components/01-elements/img/img.tsx

- [FP-928: Wire up the Image component](https://app.clickup.com/t/36718269/FP-928)
- Updates Img component
- (optional) Describes changes made to the project's README file
- Security checks that should be reviewed
- Should this be checked for this feature?
- (optional) Document any intentionally unfinished parts or known issues within this PR

FP-928: Wire up the Image component

---

src/lib/components/02-components/social-share/social-share.stories.tsx
src/lib/components/02-components/social-share/social-share.tsx

- [FP-248: Blog FED](https://fourkitchens.clickup.com/t/36718269/FP-248)
Creates the social share component

FP-248: Social share component created

---

src/lib/components/02-components/featured-resource/featured-resource--card.tsx
src/lib/components/index.ts
tailwind-theme-preset.js

- [FP-248: Blog FED](https://fourkitchens.clickup.com/t/36718269/FP-248)
- Adds an ID prop to the `featured-resource--card` component to be accesible from an anchor
- Also export the SocialShare component (adds it to the index)

FP-248: Blog FED

---

src/lib/components/02-components/callout/callout.tsx
src/lib/components/index.ts

- [FP-264: Cyber Education FE](https://fourkitchens.clickup.com/t/36718269/FP-264)

FP-264: Cyber Education FE

---

src/lib/components/02-components/search-input/search-input-simple.tsx
src/lib/components/index.ts

- [FP-956: Create 404 and 500 pages](https://fourkitchens.clickup.com/t/36718269/FP-956)
- Create simple search component

FP-956: Create 404 and 500 pages

---

src/lib/components/02-components/cta/cta.tsx
src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
src/lib/components/02-components/featured-resource/featured-resource--card.tsx
src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
src/lib/components/02-components/marketo-reference/marketo-reference.tsx
src/lib/components/02-components/slider/content-slider.tsx

- [FP-921: Product page components](https://fourkitchens.clickup.com/t/36718269/FP-921)
- Adds support for override components from FE application
- Required by https://github.com/fourkitchens/forcepoint-nextjs-page-router/pull/97

FP-921: Product page components

---

src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
src/lib/components/02-components/menus/main-menu/main-menu.tsx

- [D10 INTL Main Nav issues](https://app.asana.com/0/1203386530974194/1207516992240975/f)
- Adds spacing for rtl languages
- Revert CTA for rtl languages
- Break words that are too big on the card
- Add a big german word in the main nav story

INTL Main Nav issues

---

src/lib/components/02-components/menus/main-menu/main-menu.tsx
src/lib/components/02-components/sticky-header/sticky-header.tsx

- [FP-NOTICKET](https://fourkitchens.clickup.com/t/36718269/FP-XXX)
- Adds spacing for Header and Footer
- https://github.com/fourkitchens/forcepoint-nextjs-page-router/pull/118

FP-NOTICKET: header & footer layout

---

src/lib/components/02-components/slider/content-slider.tsx

- [FP-1043: image slider light background color](https://fourkitchens.clickup.com/t/36718269/FP-1043)
- [FP-1042: image slider title alignment and size](https://fourkitchens.clickup.com/t/36718269/FP-1042)
- Fix background for slider
- Fix main title size on slider

FP-1043, FP-1042: Slider fixes

---

README.md

https://fourkitchens.clickup.com/t/36718269/FP-737
Update the readme documentation

FP-737: Readme updated

---

src/lib/components/02-components/podcast/podcast.tsx

- [FP-1097: Podcast minor styling changes ](https://app.clickup.com/t/36718269/FP-1097)
- Adds Line height to the Podcast component (favorite platform).

FP-1097: Podcast minor styling changes

---

src/lib/components/02-components/marketo-reference/marketo-reference.stories.tsx
src/lib/components/02-components/marketo-reference/marketo-reference.tsx

- [NA: Fix form width at final plea](https://app.asana.com/0/1203386530974194/1207956230471366/f)
- Adds condition for 'centered_form_image_as_background' (max-width to 600px).

NA: Fix form width at final plea

---

docs/api/cta.md
src/lib/components/02-components/cta/cta.stories.tsx
src/lib/components/02-components/cta/cta.tsx
src/lib/components/02-components/list-item/list-item.stories.tsx
src/lib/components/02-components/list-item/list-item.tsx
src/lib/components/02-components/list/list.stories.tsx

PR to sync develop.
(Previous PR was merged directly in `main`)

Sync develop

---

src/lib/components/02-components/cta/cta.tsx
src/lib/components/02-components/table/table.tsx

- [Migration adjustments](https://app.asana.com/0/1203386530974194/1208003206491700/f)
- Add a max-width to table
- Add a max-width for the CTA content

Migration adjustments

---

src/lib/components/02-components/cta-banner/cta-banner.tsx
src/lib/components/02-components/form/hubspot-form-wrapper.tsx

- [NA: Landing Page Hero Component Is not Displaying Correctly.](https://app.asana.com/0/1203386530974194/1208022343893448)
- Adds form type: "basic-hero-banner"

NA: Landing Page Hero Component Is not Displaying Correctly.

---

src/lib/components/02-components/cta/cta.tsx

Fix link problem in CTA

---

src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx

- [Videos do not popup](https://app.asana.com/0/1203386530974194/1208090287237643/f)
- Add on click event to resource list item

Add on click event to resource list item

---

src/lib/assets/css/form.css
src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx

- Add onClick event on feature resource list item

New release September 13rd 2024

---

src/lib/assets/css/form.css
src/lib/assets/css/main-menu.css
src/lib/components/02-components/menus/main-menu/main-menu.tsx
tailwind-theme-preset.js

- [Re-Deploy Shiny sticky button (site wide) in D10](https://app.asana.com/0/1203386530974194/1208217402569841)
- Adds a shiny animation to the sticky button on the main menu page

Re-Deploy Shiny sticky button (site wide) in D10

---

src/lib/assets/css/form.css
src/lib/assets/css/main-menu.css
src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
src/lib/components/02-components/menus/main-menu/main-menu.tsx
tailwind-theme-preset.js

- [Re-Deploy Shiny sticky button (site wide) in D10](https://app.asana.com/0/1203386530974194/1208217402569841)
- Adds a shiny animation to the sticky button on the main menu page

New release September 23rd 2024

---

src/lib/components/02-components/table/data-table-provider.tsx
src/lib/components/02-components/table/table-column.tsx
src/lib/components/02-components/table/table-pager.tsx
src/lib/components/02-components/table/table-row.tsx

- [Product Page Sticky Nav Is Possessed](https://app.asana.com/0/1203386530974194/1208356309838255/f)
- Currently, some product pages have won't let the user scroll to the top on mobile
- Depends on the [latest version shared components library](https://github.com/fourkitchens/forcepoint-shared-components/pull/149)

Product Page Sticky Nav Is Possessed

---

src/lib/components/02-components/menus/footer/footer-menu.tsx
src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx

- [Change ALL External links to open in new tab/window](https://app.asana.com/0/1203386530974194/1207940610051368/f)
- Open external urls on footer and top menu in a new tab/window

Change ALL External links to open in new tab/window

---

src/lib/assets/css/theme.css
src/lib/components/02-components/table/table-column.tsx
src/lib/components/02-components/table/table-row.tsx

- [Update table component](https://app.asana.com/0/1203386530974194/1208859536220916/f)
- Update table style

Update table component

---

src/lib/components/02-components/table/table-column.tsx

- [Update table component](https://app.asana.com/0/1203386530974194/1208859536220916/f)
- Fix table on mobile

Fix table on mobile

---

src/lib/components/00-tokens/radius/radius.stories.ts
tailwind-theme-preset.js

Add new border radius value

---

src/lib/assets/img/icons/menu.svg

- [SKO Homepage](https://app.asana.com/0/1203386530974194/1209145864787695/f)
- Make color of menu icon editable

SKO Homepage

---

src/lib/assets/css/form.css

Adjust input text color

---

src/lib/assets/css/form.css

Style textarea

---

src/lib/components/01-elements/link/link.tsx
src/lib/components/02-components/cta/cta.tsx

- [Deploy the Book a Meeting with Chatbot](https://app.asana.com/0/1203386530974194/1209596072511942/f)
- Create type for link colors of Link component
- Type style object in Link component
- Cast type to fix ts error in CTA component

Fix ts error created on last PR

---

src/lib/components/02-components/slider/content-slider.tsx

- [CMS - Image & Content Slider Title style](https://app.asana.com/0/1209680819873765/1209894060326579/f)
- Fix title color of the accordion slider

CMS - Image & Content Slider Title style
